# -*- coding: utf-8 -*-
"""Untitled73.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y-kzIFqd21v6Y93v20bi0igkhetOW6F7
"""

class Solution:
  
  def romanTolnt(self,s:str)->int:
    roman = ['I','V','X','L','C','D','M']
    arabic  = [1,5,10,50,100,500,1000]
    LIST = ['','','','','','','','','','','','','','','']
    #s = input('римское число ')
    #self._s = s
    len_number = len(s)
    
    I = []
    V = []
    X = []
    L = [] 
    C = []
    D = []
    M = []
    number = s
    for i in range(len_number):
      for j in range(len(roman)):
        if number[i] == roman[j]:
          LIST[i] = arabic[j]
    LIST_NUMBER = LIST[:len_number]
    #проверка написания:
    error = 0
    count = 1
    for i in range(len_number-1):
      if number[i] not in roman:
        print('Ошибка записи числа, проверьте верность вводимых символов')
        error = 1
        break;
      if LIST_NUMBER[i] == LIST_NUMBER[i+1]:
       count = count + 1
       if (LIST_NUMBER[i] == 5 or LIST_NUMBER[i] == 50 or LIST_NUMBER[i] == 500):
         print('Ошибка написания числа, проверьте символы V,L,D, они не должны повторяться, больше одного раза')
         error = 1
         break;
       else:
         if count > 3:
           print('Ошибка написания числа, проверьте символы  I,X,C,M, они не должны повторяться больше трех раз')
           error = 1
           break;
      else: 
        count = 1
    ii_i = 0
    if error == 0:
      for i in range(len_number):
        ii = len_number - 1 - i
        ii = ii - ii_i
        #print('было',LIST_NUMBER)
        if ii > 0:
          if LIST_NUMBER[ii] < LIST_NUMBER[ii-1]:
            LIST_NUMBER[ii-1] = (LIST_NUMBER[ii] + LIST_NUMBER[ii-1])
        
          if LIST_NUMBER[ii] > LIST_NUMBER[ii-1]:
            LIST_NUMBER[ii-1] = (LIST_NUMBER[ii] - LIST_NUMBER[ii-1])
      
          if LIST_NUMBER[ii] == LIST_NUMBER[ii-1]:
            if ii > 1:
              if LIST_NUMBER[ii-1] == LIST_NUMBER[ii-2]:
                LIST_NUMBER[ii-2] = (LIST_NUMBER[ii] + LIST_NUMBER[ii-1] + LIST_NUMBER[ii-2])
                ii_i = 1
            if ii > 1:
              if LIST_NUMBER[ii-1] != LIST_NUMBER[ii-2]:
                LIST_NUMBER[ii-1] = (LIST_NUMBER[ii] + LIST_NUMBER[ii-1])
            
            else:
              LIST_NUMBER[ii-1] = (LIST_NUMBER[ii] + LIST_NUMBER[ii-1])
    #print('арабское число ',romanTolnt) 
    return LIST_NUMBER[0]
print('арабское число ',Solution().romanTolnt('XLIX'))